theme: jekyll-theme-cayman
title: [Collection of Web Safe CSS Fonts]
description: [No worries to find the appropriate fonts for your new website, Just use this CSS code and reduce your brainstorming about web safe font.]
show_downloads: ["true"]
